#!/usr/bin/env python
import os
import re
import logging
from argparse import ArgumentParser

from pubtools.pulplib import Client, Criteria, Matcher

log = logging.getLogger("set-maintenance")


def set_maintenance(client, regex):

    report = client.get_maintenance_report().result()

    crit = Criteria.with_field("id", Matcher.regex(regex))
    # search repo
    repos = self.search_repository(crit).result()

    repo_ids = [repo.id for repo in repos.as_iter()]
    report = report.add(repo_ids)
    # get the repo ids and feed to report

    tasks = client.set_maintainenance(report).result()

    report = client.get_maintenance_report().result()
    log.info("maintenance mode set: %s", report._json())

    to_remove = []
    for entry in report.entries:
        if re.match(regex, entry.id):
            to_remove.append(entry.id)

    report = report.remove(to_remove)
    tasks = client.set_maintainenance(report).result()

    report = client.get_maintenance_report().result()
    log.info("maintenance mode unset: %s", report._json())


def make_client(args):
    auth = None

    if args.username:
        password = args.password
        if password is None:
            password = os.environ.get("PULP_PASSWORD")
        if not password:
            log.warning("No password provided for %s", args.username)
        auth = (args.username, args.password)

    return Client(args.url, auth=auth, verify=not args.insecure)


def main():
    log.setLevel(logging.INFO)
    logging.basicConfig(format="%(message)s", level=logging.INFO)

    parser = ArgumentParser(description="Set/unset maintenance mode of Pulp")
    parser.add_argument("--url", help="Pulp server URL")
    parser.add_argument("--username", help="Pulp username")
    parser.add_argument(
        "--password", help="Pulp password (or set PULP_PASSWORD in env)"
    )
    parser.add_argument("--debug", action="store_true")
    parser.add_argument("--insecure", default=False, action="store_true")
    parser.add_argument("--regex", action="store")

    p = parser.parse_args()

    if not p.url:
        parser.error("--url is required")

    if not p.regex:
        parser.error("--regex is required")

    if p.debug:
        logging.getLogger("pubtools.pulplib").setLevel(logging.DEBUG)
        log.setLevel(logging.DEBUG)

    client = make_client(p)
    return set_maintenance(client, p.regex)


if __name__ == "__main__":
    main()
