#!/usr/bin/env python
import os
import logging
from argparse import ArgumentParser

from pubtools.pulplib import Client, YumRepository, FileRepository

log = logging.getLogger("upload")

METADATA_TYPES = ["productid"]


def upload_to_repo(repo, path):
    # Apply some heuristics to decide what kind of content we're uploading.
    # Note: real tools should do something more robust, e.g. require the caller
    # to lay out files into directories according to their type or otherwise
    # specify the type up-front.
    if isinstance(repo, YumRepository):
        if path.endswith(".rpm"):
            return repo.upload_rpm(path)

        if path.endswith("modules.yaml") or path.endswith("modules.yml"):
            return repo.upload_modules(path)

        # We can upload metadata file if the filename exactly matches a known
        # metadata type (e.g. "productid")
        basename = os.path.basename(path)
        if basename in METADATA_TYPES:
            return repo.upload_metadata(path, basename)

    if isinstance(repo, FileRepository):
        return repo.upload_file(path)
    raise RuntimeError("Don't know how to upload %s into %s!" % (path, repo))


def upload(client, path, repo_id):
    repo = client.get_repository(repo_id).result()

    uploads = []
    if os.path.isdir(path):
        for file in os.listdir(path):
            file = os.path.join(path, file)
            if os.path.isfile(file):
                uploads.append(upload_to_repo(repo, file))
    elif os.path.isfile(path):
        uploads.append(upload_to_repo(repo, path))

    for up in uploads:
        result = up.result()
        log.debug("Import task finished:\n%s", result)

    log.info("Uploaded %s files to repository %s", len(uploads), repo_id)


def make_client(args):
    auth = None

    if args.username:
        password = args.password
        if password is None:
            password = os.environ.get("PULP_PASSWORD")
        if not password:
            log.warning("No password provided for %s", args.username)
        auth = (args.username, args.password)

    return Client(args.url, auth=auth, verify=not args.insecure)


def main():
    log.setLevel(logging.INFO)
    logging.basicConfig(format="%(message)s", level=logging.INFO)

    parser = ArgumentParser(description="Upload files to Repository")
    parser.add_argument("--url", help="Pulp server URL")
    parser.add_argument("--repo-id", action="store")
    parser.add_argument("--path", action="store", help="Path to a file or a directory")
    parser.add_argument("--username", help="Pulp username")
    parser.add_argument(
        "--password", help="Pulp password (or set PULP_PASSWORD in env)"
    )
    parser.add_argument("--debug", action="store_true")
    parser.add_argument("--insecure", default=False, action="store_true")

    p = parser.parse_args()

    if not p.url:
        parser.error("--url is required")

    if not p.repo_id:
        parser.error("--repo-id is required")

    if not p.path:
        parser.error("--path is required")

    if p.debug:
        logging.getLogger("pubtools.pulplib").setLevel(logging.DEBUG)
        log.setLevel(logging.DEBUG)

    with make_client(p) as client:
        return upload(client, p.path, p.repo_id)


if __name__ == "__main__":
    main()
