#!/bin/sh
# Reverse dependency tester.
#
# Usage: revdep-test <git-url>
#
# This script is intended to be run within a virtualenv with latest
# version of this project installed. It'll run autotests from
# some *other* project which depends on this one.
#
# The project must satisfy requirements:
# - is itself pip-installable
# - must support py.test for test running
# - if tests need extra reqs, they must be in test-requirements.txt
#
URL="$1"

CLONE_DIR=$(mktemp -d -t --suffix=revdep)

clean(){
  rm -rf $CLONE_DIR
}
trap clean EXIT

set -xe

git clone "$URL" "$CLONE_DIR"
cd "$CLONE_DIR"

pip install --editable .
if test -e test-requirements.txt; then
  pip install -rtest-requirements.txt
fi

py.test -v
